album/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import login, logout_then_login
urlpatterns = [
    url(r'^test_project/', include('test_project.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/',login,{'template_name':'test_project/login/login.html'}, name='login'),
    url(r'^logout/',logout_then_login, name='logout')
]

test_project/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import login, logout_then_login

from . import views

app_name='test_project'
urlpatterns = [
    url(r'^$', login_required(views.index), name='index'),
    url(r'^album/', views.album, name='album'),
    url(r'^(?P<cromo_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<pagina_id>[0-9]+)/pagina/$',views.pagina, name='pagina'),

]

test_project/models.py
from django.db import models
from django.db.models.signals import post_save,pre_save
from django.contrib.auth.models import User
from django.contrib.auth import views as auth_views
from django.utils import timezone
from django.dispatch import receiver
from django.template.defaultfilters import slugify

class Pagina(models.Model):
	id=models.AutoField(primary_key=True)
	nombre=models.CharField(max_length=30)
	PAIS='Pais'
	MISCALENEO='MS'
	list_tipo=((PAIS,'Pais'),(MISCALENEO,'Miscaleneo'))
	tipo=models.CharField(max_length=30,choices=list_tipo,default=PAIS)
	def __str__(self):
		return self.nombre


class UserProfile(models.Model):
	user=models.OneToOneField(User,unique=True,on_delete=models.CASCADE)
	num_sobres=models.IntegerField(default=3)
	time_sobres=models.DateTimeField(default=timezone.now)
	def set_time(num):
		time_sobres.time.second=num


class Record(models.Model):
	title = models.CharField(max_length=15)
	text = models.CharField(max_length=)
	date = models.DateField(default=timezone.now)
	img_id = models.CharField(max_length=20)
	

class List_Cromo(models.Model):
	user_id=models.OneToOneField(User,on_delete=models.CASCADE)
	def __str__(self):
		return str(self.user_id)

class Cromo(models.Model):
	id=models.AutoField(primary_key=True)
	nombre=models.CharField(max_length=30)
	JUGADOR='Jugador'
	MISCALENEO='Miscaleneo'
	list_tipo=((JUGADOR,'Jugador'),(MISCALENEO,'Miscaleneo'))
	tipo=models.CharField(max_length=30,choices=list_tipo,default=JUGADOR)
	page_id=models.ForeignKey(Pagina,on_delete=models.CASCADE)
	pub_date=models.DateTimeField('date published')
	
	def __str__(self):
		return self.nombre
class Cromo_Rep(models.Model):
	list_cromo_id=models.ForeignKey(List_Cromo,on_delete=models.CASCADE)
	cromo=models.ForeignKey(Cromo,on_delete=models.CASCADE)
	no_repeat=models.IntegerField(primary_key=True)
	cantidad=models.IntegerField(default=0)
	def __str__(self):
		return str(self.cromo)



class Estadistica(models.Model):
	cromo_id = models.OneToOneField(Cromo, on_delete=models.CASCADE,primary_key=True, unique=True)
	posicion = models.CharField(max_length=20)
	fecha_nacimiento=models.DateTimeField()
	club = models.CharField(max_length=40)
	altura = models.CharField(max_length=10)
	peso= models.CharField(max_length=10)
	debut = models.IntegerField()
	def __str__(self):
		return str(self.cromo_id)



def create_user_profile(sender,instance,created,**kwargs):
	if created:
		profile, created = UserProfile.objects.get_or_create(user=instance)
post_save.connect(create_user_profile,sender=User)

@receiver(pre_save,sender=Cromo_Rep)
def my_callback(sender, instance, *args, **kwargs):
    instance.no_repeat = slugify(instance.list_cromo_id)




"""class Page(models.Model):
	id=models.AutoField(primary_key=True)
	nombre_des=models.CharField(max_length=20)
	#choices
	PAIS='PA'
	MISCALENEO='MS'
	list_diseño=((PAIS,'Pais'),(MISCALENEO,'Miscaleneo'))
	diseño=models.CharField(max_length=2,choices=list_diseño,default=PAIS)
	def __str__(self):
		return self.nombre_des
		
class Country(models.Model):
	page_id=models.OneToOneField(Page, on_delete=models.CASCADE,primary_key=True)
	nombre=models.CharField(max_length=20)
	def __str__(self):
		return self.nombre

class Miscaleneo(models.Model):
	page_id=models.OneToOneField(Page,on_delete=models.CASCADE,primary_key=True)
	description_text=models.CharField(max_length=300)
	description_misc=models.CharField(max_length=40)
	def __str__(self):
		return self.description_misc

class Cromo(models.Model):
	id = models.AutoField(primary_key=True)
	cromo_img=models.CharField(max_length=200)
	pub_date=models.DateTimeField('date published')
	#new add models
	page_id=models.ForeignKey(Page, on_delete=models.CASCADE)
	#choices
	JUGADOR='jr'
	ESTADIO='es'
	list_tipo=((JUGADOR,'Jugador'),(ESTADIO,'Estadio'))
	tipo=models.CharField(max_length=2,choices=list_tipo,default=JUGADOR)
	def __str__(self):
		return self.tipo

class Jugador(models.Model):
	cromo_id	=models.OneToOneField(Cromo, on_delete=models.CASCADE,primary_key=True)
	seleccion	=models.ForeignKey(Country,on_delete=models.CASCADE,default=1)
	nombres		=models.CharField(max_length=30)
	apellidos	=models.CharField(max_length=30)
	posicion	=models.CharField(max_length=20)
	peso		=models.CharField(max_length=20)
	altura		=models.CharField(max_length=20)
	club_actual	=models.CharField(max_length=40)
	f_nacimiento=models.DateField(auto_now=False, auto_now_add=False)
	def __str__(self):
		return self.nombres

class Estadio(models.Model):
	cromo_id=models.OneToOneField(Cromo,on_delete=models.CASCADE,primary_key=True)
	nombre=models.CharField(max_length=40)
	f_creacion=models.DateField(auto_now=False,auto_now_add=False)
	def __str__(self):
		return self.nombre"""

test_project/views.py
import pytz
from django.views.generic.dates import YearArchiveView

from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.template import loader
from . import models
from django.utils import timezone
from .models import *
def index(request):
	model= UserProfile
	latest_cromos_list=Cromo.objects.order_by('-pub_date')
	template=loader.get_template('test_project/album/PaginaPrincipal.html')
	server_time=timezone.now
	
	context={
		'latest_cromos_list':latest_cromos_list,
		'UserProfile':UserProfile,
		'server_time':server_time,

	}
	return HttpResponse(template.render(context,request))
	
def album(request):
	list_pagina=Pagina.objects.order_by('-id').reverse()
	template=loader.get_template('test_project/album/pagina_principal.html')
	context={
		'list_pagina':list_pagina,
	}
	return HttpResponse(template.render(context,request))

def detail(request, cromo_id):
    cromo = get_object_or_404(Cromo, pk=cromo_id)
    return render(request, 'test_project/detail.html', {'cromo': cromo})

def pagina(request,pagina_id):
	pagina= get_object_or_404(Pagina,pk=pagina_id)
	list_cromo=Cromo.objects.order_by('-id').reverse()
	context={
		'list_cromo':list_cromo,
		'pagina':pagina,
	}
	return render(request,'test_project/album/pagina.html',context)

test_project/templates/test_project/PaginaPrincipal.html
<!DOCTYPE html>
<html>
<head>
	<title>Album Mundial Rusia 2018</title>
	<link rel="stylesheet" type="text/css" href="estilos/estilopaginaprincipal.css">
	<link type="text/css" rel="stylesheet" href="css/materialize.css">
</head>
<body>
	
	<div id="Titulo">
    	<h4 class="z-depth-1 #e53935 red darken-1">Album del Mundial Rusia 2018</h4>
    </div>
	
	<div style="position: absolute; width: 33%; height: 676px">
		<div id="PaquetesDeCromos" >
			<img src="estilos/Figuritas y paquetes.png" width="80%" height="80%">
		</div>
		<div id="BotonesDeAbrir" >
			<a class="waves-effect waves-light btn-large #f4511e deep-orange darken-1" href="AbrirSobre.html">Abrir Sobre</a>
			<a class="waves-effect waves-light btn-large #f4511e deep-orange darken-1" href="CanjearCodigo.html">Canjear Codigo</a>
		</div>
		<div id="ImgAreaInter" >
			<img src="estilos/intercambio.jpg" width="80%" height="80%">
		</div>
		<div id="BotonDeArea" >
			<a class="waves-effect waves-light btn-large #f4511e deep-orange darken-1" href="AreaDeIntercambio.html">Area de Intercambio</a>
		</div>
	</div>


	<div style="position: absolute;; width: 33%; height: 676px;margin-left: 33%;">
		<div id="FigurasMedio" >
			<img src="estilos/Figuras.png" width="70%" height="70%">
		</div>
		<div id="BotonDeCromos" >
			<a class="waves-effect waves-light btn-large #f4511e deep-orange darken-1" href="MisCromos.html">Mis Cromos</a>
		</div>
	</div>
	
	<div style="width: 34%; height: 676px;margin-left: 66%;">
		<a id="regresar" class="waves-effect waves-light btn" href="Login.html">LogOut</a>
		<div id="albumdeuser" >
			<img src="estilos/Imagen de Login.png" width="100%" height="100%" align="middle">
		</div>
		<div id="BotonDeAlbum" >
			<a class="waves-effect waves-light btn-large #f4511e deep-orange darken-1" href="MiAlbum.html">Mi Album</a>
		</div>
	</div>
</body>
</html>

test_project/templates/test_project/album/Abierto.html
<!DOCTYPE html>
<html>
<head>
	<title>Abierto</title>
	<link rel="stylesheet" type="text/css" href="estilos/estiloabrirsobre.css">
	<link type="text/css" rel="stylesheet" href="css/materialize.css">
</head>
<body>
	<div id="titulosobre2">
    	<h4 class="z-depth-1 #e53935 red darken-1">Te Tocaron los Siguientes Cromos !!</h4>
    </div>
    <div id="cromostocados" >
		<img id="1" src="estilos/cromo.png" width="250px">
		<img id="2" src="estilos/cromo.png" width="250px">
		<img id="3" src="estilos/cromo.png" width="250px">
		<img id="4" src="estilos/cromo.png" width="250px">
		<img id="5" src="estilos/cromo.png" width="250px">
	</div>
	<div style="width: 34%; height: 676px;margin-left: 66%;">
		<a id="regresar" class="waves-effect waves-light btn" href="PaginaPrincipal.html">Regresar</a>
	</div>
</body>
</html>

test_project/templates/test_project/album/AbrirSobre.html
<!DOCTYPE html>
<html>
<head>
	<title>AbrirSobre</title>
	<link rel="stylesheet" type="text/css" href="estilos/estiloabrirsobre.css">
	<link type="text/css" rel="stylesheet" href="css/materialize.css">
</head>
<body>
	<div id="titulosobre">
    	<h4 class="z-depth-1 #e53935 red darken-1">Abrir Sobre de Cromos</h4>
    </div>
    <div id="paquete" >
			<img src="estilos/paquete.png" width="250px">
	</div>
	<div id="BotonAbrir" >
		<a class="waves-effect waves-light btn-large #f4511e deep-orange darken-1" href="Abierto.html">Abrir !</a>
	</div>	
	<div style="width: 34%; height: 676px;margin-left: 66%;">
		<a id="regresar" class="waves-effect waves-light btn" href="PaginaPrincipal.html">Regresar</a>
	</div>
</body>
</html>

test_project/templates/test_project/album/CanjearCodigo.html
<!DOCTYPE html>
<html>
<head>
	<title>CanjearCodigo</title>
	<link rel="stylesheet" type="text/css" href="estilos/estilocanjear.css">
	<link type="text/css" rel="stylesheet" href="css/materialize.css">
</head>
<body>
	<div id="Titulo">
    	<h4 class="z-depth-1 #e53935 red darken-1">Activa tu Codigo</h4>
    </div>
    <div id="paquete" >
		<img width="350px" src="estilos/paqueton.png">
		<img width="350px" src="estilos/paqueton.png">
	</div>
    <div id="formula" class="row">
    	<form>
			<h5>Codigo :</h5>
			<input type="text" name="codigo">
			<input class="waves-effect waves-light btn" type="submit" value="Canjear !! ">
		</form>
    </div>
    <div style="width: 34%; height: 676px;margin-left: 66%;">
		<a id="regresar" class="waves-effect waves-light btn" href="PaginaPrincipal.html">Regresar</a>
	</div>
</body>
</html>

test_project/templates/test_project/album/PaginaPrincipal.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{%block title%}Album Mundial Rusia 2018{%endblock%}</title>
	
	<link rel="stylesheet" type="text/css" href="{% static 'test_project/css/materialize.min.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'test_project/css/materialize.css' %}" />
	{%block header%}
	
	<link rel="stylesheet" type="text/css" href="{% static 'test_project/estilos/estilopaginaprincipal.css' %}" />
	
	{%endblock%}	

</head>
<body>
	<p>

	{{user.userprofile.time_sobres}}
	</p>
	{% block content %}
	
	<div id="Titulo">
    	<h4 class="z-depth-1 #e53935 red darken-1">Album del Mundial Rusia 2018</h4>
    </div>
	
	<div style="position: absolute; width: 33%; height: 676px">
		<div id="Tiempo" >
			<a id="clock" class="waves-effect waves-light btn-small"></a>
		</div>
		<div id="CantidadPaquetes" >
			<a class="btn-floating pulse #f4511e deep-orange darken-1"><i class="material-icons ">{{user.userprofile.num_sobres}}</i></a>
		</div>
		<div id="PaquetesDeCromos" >
			<img src="{% static 'test_project/estilos/Figuritas y paquetes.png '%}" width="80%" height="80%">
		</div>
		<div id="BotonesDeAbrir" >
			<a class="waves-effect waves-light btn-large #f4511e deep-orange darken-1" href="AbrirSobre.html">Abrir Sobre</a>
			<a class="waves-effect waves-light btn-large #f4511e deep-orange darken-1" href="CanjearCodigo.html">Canjear Codigo</a>
		</div>
		<div id="ImgAreaInter" >
			<img src="{% static 'test_project/estilos/intercambio.jpg'%}" width="80%" height="80%">
		</div>
		<div id="BotonDeArea" >
			<a class="waves-effect waves-light btn-large #f4511e deep-orange darken-1" href="AreaDeIntercambio.html">Area de Intercambio</a>
		</div>
	</div>


	<div style="position: absolute;; width: 33%; height: 676px;margin-left: 33%;">
		<div id="FigurasMedio" >
			<img src="{% static 'test_project/estilos/Figuras.png' %}" width="70%" height="70%">
		</div>
		<div id="BotonDeCromos" >
			<a class="waves-effect waves-light btn-large #f4511e deep-orange darken-1" href="MisCromos.html">Mis Cromos</a>
		</div>
	</div>
	
	<div style="width: 34%; height: 676px;margin-left: 66%;">
		<a id="regresar" class="waves-effect waves-light btn" href="{%url 'logout' %}">LogOut</a>
		<div id="albumdeuser" >
			<img src="{% static 'test_project/estilos/Imagen de Login.png' %}" width="100%" height="100%" align="middle">
		</div>
		<div id="BotonDeAlbum" >
			<a class="waves-effect waves-light btn-large #f4511e deep-orange darken-1" href="MiAlbum.html">Mi Album</a>
		</div>
	</div>
	{% endblock%}

	
	
		<script type="text/javascript">

	const getRemainingTime = deadline => {
  let now = new Date(),


      remainTime = (now-new Date(deadline)+ 18001000) / 1000,

   

      remainSeconds = ('0' + Math.floor(remainTime % 60)).slice(-2),
      remainMinutes = ('0' + Math.floor(remainTime / 60 % 60)).slice(-2),
      remainHours = ('0' + Math.floor(remainTime / 3600 % 24)).slice(-2),
      remainDays = Math.floor(remainTime / (3600 * 24));

  return {
    remainSeconds,
    remainMinutes,
    remainHours,
    remainDays,
    remainTime
  }
};

const countdown = (deadline,elem,finalMessage) => {
  const el = document.getElementById(elem);

  const timerUpdate = setInterval( () => {
    let t = getRemainingTime(deadline);
    el.innerHTML = `${t.remainDays}d:${t.remainHours}h:${t.remainMinutes}m:${t.remainSeconds}s`;

    if(t.remainTime <= 1) {
      clearInterval(timerUpdate);
      el.innerHTML = finalMessage;
    }

  }, 1000)
};

countdown(('{{user.userprofile.time_sobres}}').slice(0,-5), 'clock', '¡Ya empezó!');

		</script>
</body>
</html>

test_project/templates/test_project/album_test/form.html
{% extends "base.html" %}


{% block content %}

<div class='col -sm-6 col-sm-offset-3'>
<h1>{{  title  }}</h1>
<hr/>

<form method='POST' action='' enctype='multipart/form-data'>{ % csrf_token %}
<input type='submit' class='btn btn-default' value='Create Post'/>
</form>
</div>
{% endblock content %}

test_project/templates/test_project/album_test/pagina.html
{% load static %}
<!DOCTYPE html>
  <html lang="en">
    <head>
    	<title>{% block title %}{{ pagina.nombre }}{% endblock %}</title>


		{% block header %}
    		<link rel="stylesheet" type="text/css" href="{% static 'test_project/css/materialize.min.css' %}" />
			<style type="text/css">
			div.col.s1{
				background-image: url("{%static 'test_project/background_cromo.png' %}");
	        	margin: 10px;
	     	}
			</style>
		{% endblock %}

{% if list_cromo %}
<ul>
	{% for cromo in pagina.cromo_set.all %}
    <li>{{cromo.nombre}}	</li>
    {%endfor%}
{%endif%}
</ul>


    <div class="row ">
      <div class="col s7 push-s5 "><img src="{% static 'test_project/background_cromo.png'%}" border="0" width="100" height="100">asd</img></div>
      <div class="col s5 pull-s7 blue"><span class="flow-text">5-columns wide pulled to the left by 7-columns.</span></div>
    </div>

test_project/templates/test_project/album_test/pagina_principal.html
{% load static %}
<!DOCTYPE html>
  <html lang="en">
    <head>
    	<title>{% block title %}Pagina Principal{% endblock %}</title>

    	{% block header %}
    		<link rel="stylesheet" type="text/css" href="{% static 'test_project/css/materialize.min.css' %}" />
			<style type="text/css">
			div.col.s1{
	        margin: 10px;
	      }
			</style>
		{% endblock %}

	</head>

{%block footer%}
	<body>

{% if list_pagina %}
    <div class="row paginas">
    {% for pagina in list_pagina %}
         <div class="col s1 deep-purple accent-3"><a href="{%url 'test_project:pagina' pagina.id%}">{{ pagina.nombre }} </a></div>
    {% endfor %}
    
    </div>
{% endif %}

</body>
{% endblock%}

{% block java%}
		<!--Import jQuery before materialize.js-->
      <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
      <script type="text/javascript" src="{% static 'test_project/js/materialize.min.js' %}"></script>
	{% endblock %}
</html>

test_project/templates/test_project/detail.html
<h1>{{ cromo.id }}</h1>
<ul>
	{% if cromo.tipo == cromo.JUGADOR%}
    <li>{{ cromo.jugador.nombres }}</li>
    
    {% else %}
    <li>{{cromo.estadio.nombre}}</li>
    {%endif%}
</ul>

test_project/templates/test_project/index.html
<!DOCTYPE html>
  <html lang="en">
    <head>
    	<title>Login</title>
	</head>
	<body>
		<form method="post">
			{% csrf_token %}
			<div class="row">
				<div class="col-md-6 col-md-offset-3">
					<div class="form-group">
						<label for="username">Nombre de usuario: </label>
						<input class= "form-control" type="text" name="username">
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-6 col-md-offset-3">
					<div class="form-group">
						<label for="username">Contraseña: </label>
						<input class= "form-control" type="password" name="password">
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-6 col-md-offset-3">
					<div class="form-group">
						<a href="#">Olvide mi contraseña</a>
						<input class="btn btn-primary" type="submit" value="Ingresar">
					</div>
				</div>
			</div>
		</form>


	</body>
</html>

test_project/templates/test_project/login/Login.html
{%extends 'test_project/album/PaginaPrincipal.html' %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}Album del Mundial Rusia 2018{%endblock%}</title>
    {% block header %}
    <link rel="stylesheet" type="text/css" href="{% static 'test_project/estilos/estilos.css' %}">
    {% endblock%}
</head>
<body>
  {%block content%}
	<div id="log" class="row blue-grey" >
		<h4>Login</h4>

	</div>
<form method="post">
  {%csrf_token%}
  <div id="form" class="row">
    <div class="input-field col s6">
      
        <input id="username" name="username" type="text" class="form-control">
        <label class="active" for="username">Usuario</label>
    
    </div>
    <br><br><br><br>
    <div class="input-field col s6">
      
        <input id="Password" name="password" type="password" class="form-control">
        <label class="active" for="username">Password</label>
      
    </div>
    <br><br><br><br><br><br>
      <input id="sub" name="sub" class="btn btnrimary" type="submit" value="Ingresar">
  </div>
</form> 


	<div id="album" >
		<img src="{% static 'test_project/estilos/Imagen de Login.png' %}" width="100%" height="100%">
	</div>
  {%endblock%}
</body>
</html>

test_project/templates/test_project/login/Registro.html
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="estilos/estilos.css">
	<link type="text/css" rel="stylesheet" href="css/materialize.css">

	<title>Album del Mundial Rusia 2018</title>
</head>
<body>

	<div id="log" class="row blue-grey" >
		<h4>Login</h4>

	</div>
	<form action="">
	<div id="form" class="row">
    	<div class="input-field col s6">
      		<input id="newuser" type="text" class="validate">
      		<label class="active" for="newuser">Usuario</label>
    	</div>
    	<br><br><br><br>
    	<div class="input-field col s6">
      		<input id="newpass" type="password" class="validate">
      		<label class="active" for="newpass">Password</label>
    	</div>
      <br><br><br><br>
      <div class="input-field col s6">
          <input id="confirmarpassword" type="password" class="validate">
          <label class="active" for="confirmarpassword">Confirma la Contraseña</label>
      </div>
      <br><br><br><br>
      <div class="input-field col s6">
          <input id="numero" type="text" class="validate">
          <label class="active" for="numero">Numero de Celular</label>
      </div>
      <br><br><br><br>
      <div class="input-field col s6">
          <input id="correo" type="text" class="validate">
          <label class="active" for="correo">Correo</label>
      </div>
    	<br><br><br><br>
    	<input id="sub" class="waves-effect waves-light btn" type="submit" value="Submit">
  	</div>
  	</form> 


	<div id="album" >
		<img src="estilos/Imagen de Login.png" width="100%" height="100%">
	</div>
</body>
</html>